### ISSUE TITLE
Several tests fail

### ISSUE THREAD

**Issue by yurivict** [dwavesystems/dwave-hybrid#276] opened 2022-08-16 01:46 UTC
```
======================================================================
ERROR: test_bimodal_cluster_sampling_statistics (tests.test_composers.TestICM)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/disk-samsung/freebsd-ports/science/py-dwave-hybrid/work-py39/dwave-hybrid-0.6.8/tests/test_composers.py", line 398, in test_bimodal_cluster_sampling_statistics
    res = icm.run(inp).result()
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 446, in result
    return self.__get_result()
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/disk-samsung/freebsd-ports/science/py-dwave-hybrid/work-py39/dwave-hybrid-0.6.8/hybrid/core.py", line 413, in dispatch
    new_state = self.next(state, **kwargs)
  File "/disk-samsung/freebsd-ports/science/py-dwave-hybrid/work-py39/dwave-hybrid-0.6.8/hybrid/composers.py", line 404, in next
    ss1.record.energy = bqm.energies(ss1)
  File "/usr/local/lib/python3.9/site-packages/dimod/binary/binary_quadratic_model.py", line 1092, in energies
    return self.data.energies(samples_like, dtype=dtype)
  File "dimod/binary/cybqm/cybqm_template.pyx.pxi", line 360, in dimod.binary.cybqm.cybqm_float64.cyBQM_template.energies
  File "/usr/local/lib/python3.9/functools.py", line 888, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
TypeError: _as_samples_sampleset() got an unexpected keyword argument 'labels_type'

======================================================================
ERROR: test_ising_triangle_flip (tests.test_composers.TestICM)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/disk-samsung/freebsd-ports/science/py-dwave-hybrid/work-py39/dwave-hybrid-0.6.8/tests/test_composers.py", line 327, in test_ising_triangle_flip
    res = icm.run(inp).result()
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 446, in result
    return self.__get_result()
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/disk-samsung/freebsd-ports/science/py-dwave-hybrid/work-py39/dwave-hybrid-0.6.8/hybrid/core.py", line 413, in dispatch
    new_state = self.next(state, **kwargs)
  File "/disk-samsung/freebsd-ports/science/py-dwave-hybrid/work-py39/dwave-hybrid-0.6.8/hybrid/composers.py", line 404, in next
    ss1.record.energy = bqm.energies(ss1)
  File "/usr/local/lib/python3.9/site-packages/dimod/binary/binary_quadratic_model.py", line 1092, in energies
    return self.data.energies(samples_like, dtype=dtype)
  File "dimod/binary/cybqm/cybqm_template.pyx.pxi", line 360, in dimod.binary.cybqm.cybqm_float64.cyBQM_template.energies
  File "/usr/local/lib/python3.9/functools.py", line 888, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
TypeError: _as_samples_sampleset() got an unexpected keyword argument 'labels_type'

======================================================================
ERROR: test_large_sparse (tests.test_composers.TestICM)
Total energy is preserved after ICM on random samples over random graph.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/disk-samsung/freebsd-ports/science/py-dwave-hybrid/work-py39/dwave-hybrid-0.6.8/tests/test_composers.py", line 429, in test_large_sparse
    res = icm.run(inp).result()
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 446, in result
    return self.__get_result()
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/disk-samsung/freebsd-ports/science/py-dwave-hybrid/work-py39/dwave-hybrid-0.6.8/hybrid/core.py", line 413, in dispatch
    new_state = self.next(state, **kwargs)
  File "/disk-samsung/freebsd-ports/science/py-dwave-hybrid/work-py39/dwave-hybrid-0.6.8/hybrid/composers.py", line 404, in next
    ss1.record.energy = bqm.energies(ss1)
  File "/usr/local/lib/python3.9/site-packages/dimod/binary/binary_quadratic_model.py", line 1092, in energies
    return self.data.energies(samples_like, dtype=dtype)
  File "dimod/binary/cybqm/cybqm_template.pyx.pxi", line 360, in dimod.binary.cybqm.cybqm_float64.cyBQM_template.energies
  File "/usr/local/lib/python3.9/functools.py", line 888, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
TypeError: _as_samples_sampleset() got an unexpected keyword argument 'labels_type'

======================================================================
ERROR: test_small_lattice (tests.test_composers.TestICM)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/disk-samsung/freebsd-ports/science/py-dwave-hybrid/work-py39/dwave-hybrid-0.6.8/tests/test_composers.py", line 367, in test_small_lattice
    res = icm.run(inp).result()
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 446, in result
    return self.__get_result()
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/disk-samsung/freebsd-ports/science/py-dwave-hybrid/work-py39/dwave-hybrid-0.6.8/hybrid/core.py", line 413, in dispatch
    new_state = self.next(state, **kwargs)
  File "/disk-samsung/freebsd-ports/science/py-dwave-hybrid/work-py39/dwave-hybrid-0.6.8/hybrid/composers.py", line 404, in next
    ss1.record.energy = bqm.energies(ss1)
  File "/usr/local/lib/python3.9/site-packages/dimod/binary/binary_quadratic_model.py", line 1092, in energies
    return self.data.energies(samples_like, dtype=dtype)
  File "dimod/binary/cybqm/cybqm_template.pyx.pxi", line 360, in dimod.binary.cybqm.cybqm_float64.cyBQM_template.energies
  File "/usr/local/lib/python3.9/functools.py", line 888, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
TypeError: _as_samples_sampleset() got an unexpected keyword argument 'labels_type'

======================================================================
ERROR: test_triangle_flip (tests.test_composers.TestICM)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/disk-samsung/freebsd-ports/science/py-dwave-hybrid/work-py39/dwave-hybrid-0.6.8/tests/test_composers.py", line 309, in test_triangle_flip
    res = icm.run(inp).result()
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 446, in result
    return self.__get_result()
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/disk-samsung/freebsd-ports/science/py-dwave-hybrid/work-py39/dwave-hybrid-0.6.8/hybrid/core.py", line 413, in dispatch
    new_state = self.next(state, **kwargs)
  File "/disk-samsung/freebsd-ports/science/py-dwave-hybrid/work-py39/dwave-hybrid-0.6.8/hybrid/composers.py", line 404, in next
    ss1.record.energy = bqm.energies(ss1)
  File "/usr/local/lib/python3.9/site-packages/dimod/binary/binary_quadratic_model.py", line 1092, in energies
    return self.data.energies(samples_like, dtype=dtype)
  File "dimod/binary/cybqm/cybqm_template.pyx.pxi", line 360, in dimod.binary.cybqm.cybqm_float64.cyBQM_template.energies
  File "/usr/local/lib/python3.9/functools.py", line 888, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
TypeError: _as_samples_sampleset() got an unexpected keyword argument 'labels_type'

======================================================================
ERROR: test_allfixed (tests.test_decomposers.TestRoofDualityDecomposer)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/disk-samsung/freebsd-ports/science/py-dwave-hybrid/work-py39/dwave-hybrid-0.6.8/tests/test_decomposers.py", line 638, in test_allfixed
    new = RoofDualityDecomposer().run(init).result()
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 446, in result
    return self.__get_result()
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/disk-samsung/freebsd-ports/science/py-dwave-hybrid/work-py39/dwave-hybrid-0.6.8/hybrid/core.py", line 413, in dispatch
    new_state = self.next(state, **kwargs)
  File "/disk-samsung/freebsd-ports/science/py-dwave-hybrid/work-py39/dwave-hybrid-0.6.8/hybrid/decomposers.py", line 588, in next
    newsampleset.record.energy = bqm.energies(newsampleset)
  File "/usr/local/lib/python3.9/site-packages/dimod/binary/binary_quadratic_model.py", line 1092, in energies
    return self.data.energies(samples_like, dtype=dtype)
  File "dimod/binary/cybqm/cybqm_template.pyx.pxi", line 360, in dimod.binary.cybqm.cybqm_float64.cyBQM_template.energies
  File "/usr/local/lib/python3.9/functools.py", line 888, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
TypeError: _as_samples_sampleset() got an unexpected keyword argument 'labels_type'

======================================================================
ERROR: test_energy_correctness (tests.test_decomposers.TestRoofDualityDecomposer)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/disk-samsung/freebsd-ports/science/py-dwave-hybrid/work-py39/dwave-hybrid-0.6.8/tests/test_decomposers.py", line 667, in test_energy_correctness
    new = RoofDualityDecomposer().run(init).result()
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 446, in result
    return self.__get_result()
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/disk-samsung/freebsd-ports/science/py-dwave-hybrid/work-py39/dwave-hybrid-0.6.8/hybrid/core.py", line 413, in dispatch
    new_state = self.next(state, **kwargs)
  File "/disk-samsung/freebsd-ports/science/py-dwave-hybrid/work-py39/dwave-hybrid-0.6.8/hybrid/decomposers.py", line 588, in next
    newsampleset.record.energy = bqm.energies(newsampleset)
  File "/usr/local/lib/python3.9/site-packages/dimod/binary/binary_quadratic_model.py", line 1092, in energies
    return self.data.energies(samples_like, dtype=dtype)
  File "dimod/binary/cybqm/cybqm_template.pyx.pxi", line 360, in dimod.binary.cybqm.cybqm_float64.cyBQM_template.energies
  File "/usr/local/lib/python3.9/functools.py", line 888, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
TypeError: _as_samples_sampleset() got an unexpected keyword argument 'labels_type'

======================================================================
ERROR: test_sampling_mode (tests.test_decomposers.TestRoofDualityDecomposer)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/disk-samsung/freebsd-ports/science/py-dwave-hybrid/work-py39/dwave-hybrid-0.6.8/tests/test_decomposers.py", line 651, in test_sampling_mode
    new = RoofDualityDecomposer(sampling_mode=True).run(init).result()
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 446, in result
    return self.__get_result()
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/disk-samsung/freebsd-ports/science/py-dwave-hybrid/work-py39/dwave-hybrid-0.6.8/hybrid/core.py", line 413, in dispatch
    new_state = self.next(state, **kwargs)
  File "/disk-samsung/freebsd-ports/science/py-dwave-hybrid/work-py39/dwave-hybrid-0.6.8/hybrid/decomposers.py", line 588, in next
    newsampleset.record.energy = bqm.energies(newsampleset)
  File "/usr/local/lib/python3.9/site-packages/dimod/binary/binary_quadratic_model.py", line 1092, in energies
    return self.data.energies(samples_like, dtype=dtype)
  File "dimod/binary/cybqm/cybqm_template.pyx.pxi", line 360, in dimod.binary.cybqm.cybqm_float64.cyBQM_template.energies
  File "/usr/local/lib/python3.9/functools.py", line 888, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
TypeError: _as_samples_sampleset() got an unexpected keyword argument 'labels_type'

======================================================================
ERROR: tests.test_flow (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: tests.test_flow
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/local/lib/python3.9/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/disk-samsung/freebsd-ports/science/py-dwave-hybrid/work-py39/dwave-hybrid-0.6.8/tests/test_flow.py", line 31, in <module>
    from parameterized.parameterized import parameterized
ModuleNotFoundError: No module named 'parameterized'


======================================================================
ERROR: tests.test_reference_samplers (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: tests.test_reference_samplers
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/local/lib/python3.9/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/disk-samsung/freebsd-ports/science/py-dwave-hybrid/work-py39/dwave-hybrid-0.6.8/tests/test_reference_samplers.py", line 16, in <module>
    from parameterized import parameterized
ModuleNotFoundError: No module named 'parameterized'


======================================================================
ERROR: tests.test_samplers (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: tests.test_samplers
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/local/lib/python3.9/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/disk-samsung/freebsd-ports/science/py-dwave-hybrid/work-py39/dwave-hybrid-0.6.8/tests/test_samplers.py", line 20, in <module>
    from parameterized import parameterized, parameterized_class
ModuleNotFoundError: No module named 'parameterized'


======================================================================
ERROR: tests.test_utils (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: tests.test_utils
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/local/lib/python3.9/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/disk-samsung/freebsd-ports/science/py-dwave-hybrid/work-py39/dwave-hybrid-0.6.8/tests/test_utils.py", line 19, in <module>
    from parameterized import parameterized
ModuleNotFoundError: No module named 'parameterized'


======================================================================
FAIL: test_sa_concurrency (tests.test_concurrency.TestMultithreading)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/disk-samsung/freebsd-ports/science/py-dwave-hybrid/work-py39/dwave-hybrid-0.6.8/tests/test_concurrency.py", line 128, in test_sa_concurrency
    self.assertGreaterEqual(best_speedup, minimally_acceptable_speedup, info)
AssertionError: 1.3764924553291238 not greater than or equal to 1.5 : best speed-up of 1.3764924553291238 achieved within 250 runs: [1.2846494274286304, 1.332601384491939, 1.2618606851742245, 1.3045753880950934, 1.2673502204751232, 1.314371334758235, 1.3704445901465827, 1.3127113090577385, 1.2932738523844887, 1.3293111278111198, 1.3010585681292763, 1.3107103771444277, 1.3092336941234148, 1.2947487136562525, 1.2927164459132288, 1.29809734715894, 1.2892727272073905, 1.222422090829811, 1.3420058533131716, 1.3128020537182228, 1.306659613470751, 1.2939375625586627, 1.2711101929035775, 1.2870898669446105, 1.291362900115042, 1.304569142797025, 1.2922701626974191, 1.2677433366165838, 1.3764924553291238, 1.2527111011502416, 1.2886341660784848, 1.3410085710004669, 1.3117411597042814, 1.294617904808226, 1.3062343831202194, 1.2975980146237065, 1.2800701362190208, 1.2590264434107472, 1.3222321272350082, 1.2378025884586035, 1.3545387857900346, 1.2972178299564763, 1.236368715191112, 1.314483585479688, 1.2924303905718044, 1.3143727241085923, 1.2989247885605713, 1.3094480950022491, 1.325146623582676, 1.3198743532274366, 1.291856517947801, 1.33122757384423, 1.314482188696635, 1.2886248012774877, 1.3131366521289125, 1.3326590821391089, 1.3062513359171, 1.3551286072825217, 1.3376701053275482, 1.2745326262578975, 1.34705023277013, 1.3002022582546078, 1.3104682804276526, 1.3127420746208118, 1.3267926266051986, 1.3241551438013643, 1.3063092964159004, 1.3032089538029228, 1.2809627214426431, 1.319667066931426, 1.319334596026664, 1.3150373473381511, 1.300778537821062, 1.3175393505825428, 1.3177484002280377, 1.3209867516128269, 1.3068671824563511, 1.3224711741430586, 1.311202541690367, 1.300102631190897, 1.3161903941368263, 1.3306094988548582, 1.3074417424071105, 1.304640780062705, 1.3148478234178844, 1.300846907557742, 1.30730891541737, 1.3100792483009092, 1.3247871342795083, 1.301857182140169, 1.3128828434690953, 1.3177674390205303, 1.2957599340452195, 1.3185331278711667, 1.3180176663988776, 1.3054323109770258, 1.3111956077521545, 1.3023737478424806, 1.3081841725768049, 1.3311094132314105, 1.3082229736038613, 1.311231310810069, 1.3132660948351347, 1.3121661911338267, 1.306216133163508, 1.3180108621507245, 1.3088205813674942, 1.3228122455509088, 1.3120510520322601, 1.3222811392032863, 1.2991966574089844, 1.3098092078389094, 1.317316177245845, 1.3181256940379873, 1.3090833391049235, 1.3152877488605417, 1.2961949513511164, 1.2979486857525682, 1.318748396642347, 1.3288234493855076, 1.3067551393734091, 1.3145349098834698, 1.3051103116978542, 1.3165267855120963, 1.324670346890857, 1.3210259986394524, 1.3175295671553793, 1.311361842026564, 1.3011766300582042, 1.3154645284557445, 1.3160838980525396, 1.312858288615751, 1.3169427106930234, 1.3134075242930665, 1.275197108091771, 1.2995967076574082, 1.3065846690872844, 1.3204056050564283, 1.314003031766049, 1.3259309504666617, 1.321118514634426, 1.3048142456118432, 1.3165577339831684, 1.3121075555613122, 1.3066996161688493, 1.3119623602611512, 1.3120837681166961, 1.3016398185805076, 1.260522825370384, 1.3156557392135133, 1.3009066748365374, 1.341040158400286, 1.2912242074341962, 1.2887008119608705, 1.343623188992217, 1.289595397325202, 1.3145607157870545, 1.3005142335688014, 1.319804883293057, 1.3736610469862383, 1.333346793909288, 1.305932830454033, 1.323884130206583, 1.3117217159048327, 1.328027050648461, 1.313278121982859, 1.3142883120505673, 1.3219841794597436, 1.2841488262894982, 1.3106616518541858, 1.3094740531089768, 1.2795080071998433, 1.3008650231551402, 1.3234250512598462, 1.2807757652751668, 1.3104999788912608, 1.313782528707344, 1.3102152642796498, 1.3135503680103024, 1.3094475240298187, 1.3077846673323892, 1.312805685284761, 1.3226808743289644, 1.3029612842538558, 1.3249664429039756, 1.2961508442935914, 1.3185379898494314, 1.2951245253871582, 1.304828040529385, 1.2918296966491063, 1.3169752340196488, 1.3225120508552595, 1.3377027597312714, 1.3150255933194308, 1.2999620623377508, 1.3079338680029802, 1.3253456374097794, 1.30296791655022, 1.3237059374164817, 1.309226297133855, 1.3114023592454291, 1.2910007095191567, 1.2964238945209081, 1.2955308527148195, 1.304244705718231, 1.3199711498130944, 1.2934131096765111, 1.2912378931978894, 1.3028762421777929, 1.3112798608429346, 1.3074189888564212, 1.3255963879043005, 1.3062666964825411, 1.3134192445154658, 1.309708293719782, 1.3155043884144833, 1.3036601133582666, 1.2990373879831174, 1.3071250944221333, 1.294225096203217, 1.3146403194397212, 1.3180392687760862, 1.3118748492424641, 1.3076127590909727, 1.3010696238338693, 1.3169588726113937, 1.3051617103884505, 1.3111709993245597, 1.2950110799565566, 1.3078532244071588, 1.3013822734036657, 1.3226460866660403, 1.3087410280495004, 1.3112538496830077, 1.314409726314922, 1.30392796723841, 1.3139903109309763, 1.2887584734772093, 1.3176014231571658, 1.3065966907097266, 1.30206431938632, 1.3163396751081906, 1.298556468776358, 1.3031922896707904, 1.3343447326781577, 1.3030839842806867, 1.3068708371879878, 1.312725234294067, 1.3253816551114672, 1.3186222732466546]

----------------------------------------------------------------------
Ran 156 tests in 2738.710s

FAILED (failures=1, errors=12)
*** Error code 1
```

Version: 0.6.8
Python-3.9
FreeBSD 13.1

**Comment by randomir** [comment] 2022-08-16 14:35
Could you please share the reproduction steps?

I see you're missing test requirements, but other than that, not sure why it fails for you.

```
$ git clone https://github.com/dwavesystems/dwave-hybrid
$ cd dwave-hybrid
$ python -m venv env
$ . env/bin/activate
(env) $ pip install -r requirements.txt -r tests/requirements.txt
(env) $ python -m unittest
........................................................................................................../tmp/dwave-hybrid/env/lib/python3.9/site-packages/networkx/convert.py:136: ImportWarning: pandas not found, skipping conversion test.
  warnings.warn("pandas not found, skipping conversion test.", ImportWarning)
.....................................................................................................................................................................................................................................
----------------------------------------------------------------------
Ran 335 tests in 17.229s

OK
```

**Comment by randomir** [comment] 2022-08-16 14:42
Oh, I see, the tests fail with the latest patch release of dimod, `dimod==0.11.4`.

@arcondello, I haven't checked the code yet, but this looks like a bug in dimod, no?

**Comment by arcondello** [comment] 2022-08-16 14:42
Yes, it's a known issue, fixed by https://github.com/dwavesystems/dimod/pull/1230. I can go ahead and make a deploy seeing as it's come up twice.

See also https://github.com/dwavesystems/dwave-preprocessing/issues/44

**Comment by randomir** [comment] 2022-08-16 14:46
Then I don't think we need to rush with a release. It will be fixed in next Ocean release. Currently Ocean 5.3.0 installs [dimod 0.11.3](https://github.com/dwavesystems/dwave-ocean-sdk/blob/09acb4771a2c21580fb31a29810483fe5ffff4e5/setup.cfg#L28).

**Comment by arcondello** [comment] 2022-08-16 14:47
[Too late!](https://github.com/dwavesystems/dimod/releases/tag/0.11.5) :smiley:

**Comment by randomir** [comment] 2022-08-16 14:51
In that case, I'll close this issue :tada:

**Closed by randomir** 2022-08-16 14:51 UTC

**Comment by yurivict** [comment] 2022-09-15 23:48
Tests are still failing with dimod-0.11.5

**Comment by randomir** [comment] 2022-09-16 10:28
Hey @yurivict, I can't reproduce it.

I've tried with Ocean 5.4.0 packages:
```
certifi==2022.9.14
charset-normalizer==2.1.1
click==8.1.3
codecov==2.1.12
coverage==6.4.4
dimod==0.11.5
diskcache==5.4.0
dwave-cloud-client==0.10.2
dwave-greedy==0.2.5
dwave-hybrid==0.6.9
dwave-inspector==0.3.0
dwave-neal==0.5.9
dwave-networkx==0.8.12
dwave-ocean-sdk==5.4.0
dwave-preprocessing==0.4.0
dwave-system==1.15.0
dwave-tabu==0.4.5
dwavebinarycsp==0.2.0
fasteners==0.18
Flask==2.2.2
homebase==1.0.1
idna==3.4
importlib-metadata==4.12.0
itsdangerous==2.1.2
Jinja2==3.1.2
MarkupSafe==2.1.1
minorminer==0.2.9
networkx==2.8.6
numpy==1.23.3
parameterized==0.8.1
penaltymodel==1.0.2
plucky==0.4.3
pydantic==1.10.2
PySocks==1.7.1
python-dateutil==2.8.2
rectangle-packer==2.0.1
requests==2.28.1
scipy==1.9.1
six==1.16.0
typing_extensions==4.3.0
urllib3==1.26.12
Werkzeug==2.2.2
zipp==3.8.1
```
and all tests pass.

Can you share your `pip freeze` output please? Thanks!
